# Generated by Django 3.2.2 on 2021-05-12 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_appoint',
            field=models.DateField(default=datetime.datetime(2021, 5, 12, 18, 11, 26, 185578)),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(),
        ),
    ]
